export interface BetterDesignTheme {
  id: string;
  label: string;
  description: string;
}

export const BETTER_DESIGN_THEMES = [
  { id: "airbnb", label: "Airbnb", description: "Airbnb-inspired better-design system." },
  { id: "apple", label: "Apple", description: "Bright, rounded, soft shadows." },
  { id: "beam-lib", label: "Beam Lib", description: "Animated beam-accent better-design system." },
  { id: "carbon", label: "Carbon", description: "Carbon-inspired better-design system." },
  { id: "cinematic-dark", label: "Cinematic Dark", description: "Cinematic dark better-design system." },
  { id: "clicky", label: "Clicky", description: "Tactile interaction-focused better-design system." },
  { id: "corporate-fintech", label: "Corporate Fintech", description: "Professional fintech better-design system." },
  { id: "dark-orange", label: "Dark Orange", description: "Dark better-design system with orange accents." },
  { id: "editorial-dark", label: "Editorial Dark", description: "Dark editorial better-design system." },
  { id: "editorial-warm", label: "Editorial Warm", description: "Warm editorial better-design system." },
  { id: "figma", label: "Figma", description: "Figma-inspired better-design system." },
  { id: "glassmorphic-dark", label: "Glassmorphic Dark", description: "Dark translucent glass better-design system." },
  { id: "inset-dark", label: "Inset Dark", description: "Inset shadow dark better-design system." },
  { id: "light-marketplace", label: "Light Marketplace", description: "Light marketplace better-design system." },
  { id: "linear", label: "Linear", description: "Dark developer-tool, purple primary." },
  { id: "linear-quality", label: "Linear Quality", description: "Linear-inspired quality better-design system." },
  { id: "lumen-dark", label: "Lumen Dark", description: "Luminous dark better-design system." },
  { id: "metal-fx-chromatic", label: "Metal FX Chromatic", description: "Chromatic metallic better-design system." },
  { id: "metal-fx-gold", label: "Metal FX Gold", description: "Gold metallic better-design system." },
  { id: "metal-fx-silver", label: "Metal FX Silver", description: "Silver metallic better-design system." },
  { id: "midnight-glass", label: "Midnight Glass", description: "Midnight blue glass better-design system." },
  { id: "minimal-light", label: "Minimal Light", description: "Minimal light better-design system." },
  { id: "monochrome-industrial", label: "Monochrome Industrial", description: "Industrial monochrome better-design system." },
  { id: "neutral-monochrome", label: "Neutral Monochrome", description: "Neutral monochrome better-design system." },
  { id: "notion", label: "Notion", description: "Document-style, warm neutrals." },
  { id: "pebble", label: "Pebble", description: "Soft pebble-like better-design system." },
  { id: "pillow-light", label: "Pillow Light", description: "Soft low-contrast light better-design system." },
  { id: "precision-light", label: "Precision Light", description: "Precise light professional better-design system." },
  { id: "romanesque", label: "Romanesque", description: "Serif editorial better-design system." },
  { id: "skeuo-next", label: "Skeuo Next", description: "Modern skeuomorphic better-design system." },
  { id: "sonic-airy", label: "Sonic Airy", description: "Airy Sonic-inspired better-design system." },
  { id: "sonic-bright", label: "Sonic Bright", description: "Bright Sonic-inspired better-design system." },
  { id: "sonic-glassy", label: "Sonic Glassy", description: "Glassy Sonic-inspired better-design system." },
  { id: "sonic-lofi", label: "Sonic Lofi", description: "Lofi Sonic-inspired better-design system." },
  { id: "sonic-metallic", label: "Sonic Metallic", description: "Metallic Sonic-inspired better-design system." },
  { id: "sonic-organic", label: "Sonic Organic", description: "Organic Sonic-inspired better-design system." },
  { id: "sonic-punchy", label: "Sonic Punchy", description: "Punchy Sonic-inspired better-design system." },
  { id: "sonic-retro", label: "Sonic Retro", description: "Retro Sonic-inspired better-design system." },
  { id: "sonic-warm", label: "Sonic Warm", description: "Warm Sonic-inspired better-design system." },
  { id: "squircle", label: "Squircle", description: "Squircle-radius better-design system." },
  { id: "stripe", label: "Stripe", description: "Commercial dashboard, blue primary." },
  { id: "supabase", label: "Supabase", description: "Developer dashboard, green accents." },
  { id: "tv-style", label: "TV Style", description: "TV-inspired better-design system." },
  { id: "vercel", label: "Vercel", description: "Minimal black & white." },
  { id: "vibrant-dark", label: "Vibrant Dark", description: "Vibrant dark better-design system." },
] as const satisfies readonly BetterDesignTheme[];

export const BETTER_DESIGN_COMPONENTS = [
  "accordion",
  "alert",
  "avatar",
  "badge",
  "breadcrumb",
  "border-beam",
  "button",
  "card",
  "calendar",
  "chart",
  "code-block",
  "copy-button",
  "data-table",
  "dialog",
  "dropdown-menu",
  "empty",
  "field",
  "form",
  "input",
  "kbd",
  "label",
  "metal-ring",
  "notification",
  "pagination",
  "popover",
  "progress",
  "rating",
  "scroll-area",
  "section-header",
  "select",
  "separator",
  "skeleton",
  "spinner",
  "sound-provider",
  "stat-card",
  "status-indicator",
  "steps",
  "table",
  "tabs",
  "textarea",
  "timeline",
  "tooltip",
  "typography",
  "_shared",
] as const;
