#!/usr/bin/env node
// Pull CSS variables for each better-design theme and emit a scoped `.theme-<slug>`
// rule under `themes/<slug>/theme.css`.
//
// Run via: `pnpm fetch:themes` (see package.json).

import { promises as fs } from "node:fs";
import path from "node:path";
import { BETTER_DESIGN_THEMES } from "../src/lib/betterDesignCatalog.ts";

const REGISTRY_BASE = "https://www.better-design.com/registry";

interface RegistryEntry {
  cssVars?: {
    light?: Record<string, string>;
    dark?: Record<string, string>;
  };
}

async function fetchTheme(slug: string) {
  // Any registry entry carries the cssVars; button.json is universal.
  const res = await fetch(`${REGISTRY_BASE}/${slug}/button.json`);
  if (!res.ok) throw new Error(`fetch ${slug}: HTTP ${res.status}`);
  return (await res.json()) as RegistryEntry;
}

function buildCss(slug: string, entry: RegistryEntry): string {
  const light = entry.cssVars?.light ?? {};
  const lightLines = Object.entries(light)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  // Some themes only publish `light` — that *is* the theme's palette. We apply
  // it unconditionally under `.theme-<slug>`. A `dark` block, when present, is
  // applied when the parent also carries `.dark`.
  let css = `/* Auto-generated by scripts/fetch-themes.ts — do not edit by hand. */
.theme-${slug} {
${lightLines}
}\n`;
  const dark = entry.cssVars?.dark;
  if (dark && Object.keys(dark).length > 0) {
    const darkLines = Object.entries(dark)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join("\n");
    css += `\n.dark.theme-${slug},\n.dark .theme-${slug} {\n${darkLines}\n}\n`;
  }
  return css;
}

async function main() {
  const root = process.cwd();
  const slugs = BETTER_DESIGN_THEMES.map((theme) => theme.id);
  for (const slug of slugs) {
    process.stdout.write(`fetching ${slug}… `);
    const entry = await fetchTheme(slug);
    const css = buildCss(slug, entry);
    const dir = path.join(root, "src", "themes", slug);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, "theme.css"), css);
    process.stdout.write("ok\n");
  }
  // Aggregator that globals.css can @import.
  const aggregator = slugs.map((s) => `@import "../themes/${s}/theme.css";`).join("\n") + "\n";
  await fs.writeFile(path.join(root, "src", "lib", "themes.css"), aggregator);
  console.log(`\nwrote ${slugs.length} themes + src/lib/themes.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
